ALTER PROC dbo.PrcCalculateLoan_LAP
(
	@LEADPK		BIGINT,
	@PrdCode	VARCHAR(20)
)
AS
BEGIN 

		DECLARE @ReturnLoanTable AS TABLE (
					PRD_CODE		VARCHAR(50),
					OUTSTD_AMT		NUMERIC(27,2), 
					ARR_OUTSTD_AMT	NUMERIC(27,2), 
					TOPUP_AMT		NUMERIC(27,2), 
					ARR_TOPUP_AMT	NUMERIC(27,2), 
					BT_EMI			NUMERIC(27,2), 
					TOPUP_EMI		NUMERIC(27,2), 
					LOAN_AMT		NUMERIC(27,2), 
					EMI				NUMERIC(27,2), 
					FOIR			NUMERIC(27,2),
					ROI				NUMERIC(27,2),
					LTV				NUMERIC(27,2),
					EXP_LOAN_AMT	NUMERIC(27,2), 
					EXP_EMI			NUMERIC(27,2), 
					EXP_ROI			VARCHAR(20),
					TENURE			INT,
					CIBIL			INT,
					MRK_PRP			NUMERIC(27,2),
					INCOME			NUMERIC(27,2),
					SAL_TYPE		INT,
					SAL_PRF			INT,
					OBLIGATIONS		NUMERIC(27,2),
					ACT_PRP_VAL		NUMERIC(27,2),
					LTV_PERC_New	NUMERIC(27,2),
					FOIR_PERC_New	NUMERIC(27,2),
					SHPLR			NUMERIC(27,2),
					Loan_Amt_New	NUMERIC(27,2),
					ActLTV			NUMERIC(27,2),
					BT_LTV_A		NUMERIC(27,2),
					TOPUP_LTV_A		NUMERIC(27,2),
					BT_LTV_M		NUMERIC(27,2),
					TOPUP_LTV_M		NUMERIC(27,2)
				)

	DECLARE @INCOME	NUMERIC(27,2),@OBLIGATIONS NUMERIC(27,2),@EXPLOAN NUMERIC(27,2),@TENURE	INT,@MRKPROP_VAL NUMERIC(27,2),@LTV_PERC NUMERIC(27,2), @FOIR NUMERIC(27,2),@SHPLR NUMERIC(27,2) ,@SALARY_TYPE VARCHAR(5),@SAL_PROOF BIT,@CIBIL INT	, @ACT_PRP_VAL NUMERIC(27,2)

	SELECT @SHPLR = 18.00

	DECLARE @TEMPLOAN_AMT NUMERIC(27,2),@TEMPEMI	NUMERIC(27,2),@TEMPFOIR NUMERIC(27,2),@TEMPROI	NUMERIC(27,2),@TEMPLTV	NUMERIC(27,2) , 
			@EXP_EMI NUMERIC(27,2), @EXP_ROI VARCHAR(20),@LTV_PERC_A NUMERIC(27,2),
			@BT_LTV_A NUMERIC(27,2),@TOPUP_LTV_A NUMERIC(27,2),@BT_LTV_M NUMERIC(27,2),@TOPUP_LTV_M NUMERIC(27,2)


	DECLARE @CurDt DATETIME, @TranCount INT = 0, @ErrSeverity INT, @ErrMsg VARCHAR(MAX), @Error INT, @RowCount INT

	DECLARE @TempAppTable AS TABLE (LEADPK BIGINT , LAPPK BIGINT , CIBIL INT, INCOME NUMERIC(27,2), OBLIGATION NUMERIC(27,2), SALARYTYPE VARCHAR(5) ,
						 SALPROOF BIT ,EXPLOAN NUMERIC(27,2) , TENURE INT , MRKPROP_VAL NUMERIC(27,2) , EXP_EMI NUMERIC(27,2) , EXP_ROI VARCHAR(20),ACT_PRPVAL NUMERIC(27,2))


	DECLARE @SalarySUmmary AS TABLE (LeadPk BIGINT, LapFk BIGINT , Salary NUMERIC(27,2) , Percentage NUMERIC(27,2) , addless TINYINT )
	DECLARE  @BnkBal AS TABLE (LeadPk BIGINT, LapFk BIGINT , Salary NUMERIC(27,2) , Percentage NUMERIC(27,2) , addless TINYINT , Pk BIGINT)

	DECLARE @ObligationSummary  AS TABLE (LeadPk BIGINT , LapFk BIGINT , Obligation NUMERIC(27,2))

	DECLARE @INCOMEOBL AS TABLE (LeadPk BIGINT ,LapFk BIGINT , Income NUMERIC(27,2), Obligation NUMERIC(27,2))

	DECLARE @TempCreditTable AS TABLE (CreditPk BIGINT )

	DECLARE @OutSandAmt NUMERIC(27,2) = 0,@ARR_OutSandAmt NUMERIC(27,2) = 0 , 
			@TopUpAmt NUMERIC(27,2) = 0 ,  @ARR_TopUpAmt NUMERIC(27,2) = 0,
			@BT_EMI NUMERIC(27,2) = 0,@TOPUP_EMI NUMERIC(27,2) = 0 , @IsPNI CHAR(1) , @GRPCD VARCHAR(20)

		SELECT @GRPCD = GrpCd FROM GenLvlDefn (NOLOCK) 
		JOIN GenPrdMas (NOLOCK) ON PrdGrpFk = GrpPk  AND PrdDelId = 0
		WHERE PrdCd = @PrdCode  

	
		-- calculation of income and obligations
		INSERT INTO @INCOMEOBL(LeadPk,LapFk,Income, Obligation)
		SELECT	@LEADPK, LioLapFk,ISNULL(SUM(LioSumAMt),0),0 
		FROM	LosAppIncObl (NOLOCK)
		WHERE	LioLedfk = @LEADPK AND LiodeLid = 0 AND LioType <> 'OB'
		GROUP BY LioLapFk


		SELECT ISNULL(SUM(LioSumAMt),0) Obl,LioLapFk LapFk 
		INTO #TempOblTable
		FROM LosAppIncObl (NOLOCK)
		WHERE	LioLedfk = @LEADPK AND LiodeLid = 0 AND LioType = 'OB'
		GROUP BY LioLapFk

		UPDATE	T  SET T.Obligation = A.Obl
		FROM	@INCOMEOBL  T
		JOIN	#TempOblTable A ON A.LapFk = T.LapFk

		INSERT INTO @TempAppTable 
							(	LEADPK , LAPPK , CIBIL , INCOME , OBLIGATION , SALARYTYPE , SALPROOF , EXPLOAN ,TENURE, MRKPROP_VAL , EXP_EMI, EXP_ROI,ACT_PRPVAL )
		SELECT	DISTINCT		Ledpk ,LapPk ,  LapCibil , ISNULL(Income ,0), ISNULL(Obligation,0) , AppSalTyp , AppSalPrf , LedLnAmt , LedTenure ,  
								SUM(ISNULL(LptMktVal,0)) , LedEMI , REPLACE(LedROI, '%', '') AS LedROI,SUM(ISNULL(LplAgrmtVal,0))
		FROM	LosAppProfile(NOLOCK)
				JOIN	LosLead(NOLOCK) ON LedPk  = LapLedFk AND LedDelId = 0
				JOIN	LosApp(NOLOCK) ON AppLedFk = LedPk AND LapAppFk = AppPk AND AppDelId=0
				LEFT OUTER JOIN	@INCOMEOBL ON LapFk = LapPk AND LeadPk = LapLedFk
				LEFT OUTER JOIN	LosPropTechnical(NOLOCK) ON LptLedFk =  LedPk AND LptDelId = 0
				LEFT OUTER JOIN	LosPropLegal(NOLOCK) ON LplLedFk =  LedPk AND LplDelId = 0
		WHERE	LedPk = @LEADPK AND LapDelId = 0		
		GROUP BY Ledpk,LapPk ,  LapCibil,Income,Obligation,AppSalTyp,AppSalPrf,LedLnAmt,LedTenure,LedEMI,LedROI

		
		SELECT	@INCOME = ROUND(ISNULL(SUM(INCOME),0),0), @OBLIGATIONS = ISNULL(SUM(OBLIGATION) ,0)
		FROM	@TempAppTable;				
		
		SELECT	@CIBIL = MAX(CIBIL)
		FROM	@TempAppTable WHERE CASE WHEN @GRPCD = 'LAP' THEN (ISNULL(INCOME,0) - ISNULL(OBLIGATION,0)) ELSE ISNULL(INCOME,0) END > 0 ;

		IF @CIBIL > 0 AND @CIBIL <= 6
			SET @CIBIL = 0

		SELECT	@SALARY_TYPE = SALARYTYPE , @SAL_PROOF = SALPROOF , @EXPLOAN = EXPLOAN ,
				@TENURE =TENURE ,@EXP_EMI = EXP_EMI , @EXP_ROI = EXP_ROI
		FROM	@TempAppTable;	
		
		SELECT  Ledpk , MIN(LptMktVal) LptMktVal,MIN(LplAgrmtVal) LplAgrmtVal,Lptprpfk
		INTO	#TempProp
		FROM	LosLead (NOLOCK)
		JOIN	LosApp(NOLOCK) ON AppLedFk = LedPk AND AppDelId=0
		LEFT OUTER JOIN	LosPropTechnical(NOLOCK) ON LptLedFk =  LedPk AND LptDelId = 0
		LEFT OUTER JOIN	LosPropLegal(NOLOCK) ON LplLedFk =  LedPk AND LplDelId = 0
		WHERE	LedPk = @LEADPK AND LedDelid= 0	
		GROUP BY Lptprpfk,Ledpk

		SELECT	@MRKPROP_VAL = ISNULL(SUM(LptMktVal),0),@ACT_PRP_VAL= ISNULL(SUM(LplAgrmtVal),0) 
		FROM	#TempProp
			
				
		SELECT	@OutSandAmt = ISNULL(SUM(LelOutstandingAmt) ,0)
		FROM	LosAppExistLn(NOLOCK) WHERE LelLedFk = @LEADPK

		IF(@PrdCode = 'LAPTopup')
		BEGIN
			SELECT @EXPLOAN = @EXPLOAN + @OutSandAmt
		END		

		SELECT @IsPNI = LedPNI FROM LosLead(NOLOCK) WHERE LedPk = @LEADPK AND LedDelId = 0 		

		-- SET The Markert value mentioned in Lead if it is PNI Case
		IF @MRKPROP_VAL = 0 AND @IsPNI <> 'Y' AND 
			EXISTS(SELECT 'X' FROM LosLead(NOLOCK) WHERE LedPk = @LEADPK AND LedDelId = 0)
		BEGIN
			SELECT @MRKPROP_VAL = ISNULL(LedMrktVal,0) FROM LosLead(NOLOCK) WHERE LedPk = @LEADPK AND LedDelId = 0
		END

		--INCOME, OBLIGATIONS, EXPLOAN, TENURE, MRKPROP_VAL, LTV_PERC , FOIR, SHPLR, SALARY_TYPE , SAL_PROOF, CIBIL , AGR_PROPVAL
		--SELECT  @INCOME 'income',@EXPLOAN 'Exploan',@TENURE 'tenure',@MRKPROP_VAL 'markval',@LTV_PERC 'ltv perc',@FOIR 'foir',@SHPLR 'shplr',@SALARY_TYPE 'saltype',@SAL_PROOF 'Proof',@CIBIL 'cibl'


		DECLARE  @ISZERO VARCHAR(20) = '';
		DECLARE @MINPROPVALUE NUMERIC(27,2) , @MIN_LTV NUMERIC(27,2);

        IF (@ACT_PRP_VAL > 0)
            SELECT @MINPROPVALUE = CASE WHEN @ACT_PRP_VAL < @MRKPROP_VAL THEN @ACT_PRP_VAL ELSE @MRKPROP_VAL END
        ELSE
            SELECT @MINPROPVALUE = @MRKPROP_VAL;        
		
		if (@ACT_PRP_VAL = 0 AND @MRKPROP_VAL = 0)
            SELECT @ISZERO = 'YES';

		IF @MINPROPVALUE <> 0
			SELECT @MIN_LTV = ( @EXPLOAN / @MINPROPVALUE ) * 100; 
		ELSE
			SELECT @MIN_LTV =  0;

		IF @MRKPROP_VAL <> 0
			SELECT @LTV_PERC =  ( @EXPLOAN / @MRKPROP_VAL ) * 100; 
		ELSE
		BEGIN
			SELECT @LTV_PERC = 0
		END

		IF @ACT_PRP_VAL <> 0
			SELECT @LTV_PERC_A =  ( @EXPLOAN / @ACT_PRP_VAL ) * 100; 
		ELSE
		BEGIN
			SELECT @LTV_PERC_A = 0
		END		

		--LOAN AMT BASED ON LTV        
        DECLARE @LOAN_AMT_LTV NUMERIC(27,2)	

		SELECT @LOAN_AMT_LTV = ISNULL(@MINPROPVALUE,0) * (ISNULL(@MIN_LTV,50) / 100);		


		--SELECT @LOAN_AMT_LTV 'lvtamt'

		--LOAN AMT BASED ON FOIR 
        DECLARE @ROI NUMERIC(27,7) = @SHPLR / 12 / 100;

		DECLARE @NAMI NUMERIC(27,7) = ISNULL(@INCOME - @OBLIGATIONS,0)

		SELECT @FOIR = CASE	WHEN @NAMI <= 10000 THEN 40
							WHEN @NAMI > 10000 AND @NAMI <= 15000 THEN 40
							WHEN @NAMI > 15000 AND @NAMI <= 30000 THEN 45
							WHEN @NAMI > 30000 THEN  50 
						END
		-- FOIR AMOUNT

		DECLARE @FOIR_AMT NUMERIC(27,2) = (ISNULL(@INCOME - @OBLIGATIONS,0) * (@FOIR / 100)) ;

		-- X-FACTOR
		DECLARE @X_FACTOR NUMERIC(27,7) = POWER((1 + @ROI), @TENURE);

		-- LOAN AMT BASED ON FOIR 
		DECLARE @LOAN_AMT_FOIR NUMERIC(27,2)= (@FOIR_AMT / @ROI) * ((@X_FACTOR - 1) / @X_FACTOR);

--SELECT @LOAN_AMT_FOIR 'FOIR'
--SELECT @LOAN_AMT_LTV 'LTV'
--SELECT @EXPLOAN 'EXP'

		--LOAN AMT BASED ON FOIR
        DECLARE @FINAL_LOAN_AMT NUMERIC(27,2) = CASE WHEN @LOAN_AMT_LTV < @LOAN_AMT_FOIR THEN ( CASE WHEN @LOAN_AMT_LTV < @EXPLOAN THEN @LOAN_AMT_LTV ELSE @EXPLOAN END)
												ELSE ( CASE WHEN @LOAN_AMT_FOIR < @EXPLOAN THEN  @LOAN_AMT_FOIR ELSE @EXPLOAN END ) END
--SELECT @FINAL_LOAN_AMT 'LAON'
--SELECT @ISZERO 'ISZERO'

		IF (@ISZERO <> '')
        BEGIN
			SELECT @FINAL_LOAN_AMT = CASE WHEN @LOAN_AMT_LTV < @LOAN_AMT_FOIR THEN
										( CASE WHEN @LOAN_AMT_FOIR < @EXPLOAN THEN  @LOAN_AMT_FOIR ELSE @EXPLOAN END ) END
		END
				

		--TEMP EMI
        DECLARE @TEMP_EMI NUMERIC(27,2) = @FINAL_LOAN_AMT * @ROI * (@X_FACTOR / (@X_FACTOR - 1));		

		--ARRIVED LTV FOR FINAL LOAN AMOUNT
        DECLARE @ARR_LTV NUMERIC(27,2)
		IF @MRKPROP_VAL <> 0
			SELECT @ARR_LTV = (@FINAL_LOAN_AMT / @MRKPROP_VAL) * 100;
		ELSE
			SELECT @ARR_LTV = 0;

		IF @ACT_PRP_VAL <> 0
			SELECT @LTV_PERC_A =  ( @FINAL_LOAN_AMT / @ACT_PRP_VAL ) * 100; 
		ELSE
			SELECT @LTV_PERC_A = 0
			
		--ARRIVED FOIR FOR FINAL LOAN AMOUNT -- IIR FOR LAP
		DECLARE @ARR_FOIR NUMERIC(27,2)
		IF @INCOME <> 0
			SELECT @ARR_FOIR = (@TEMP_EMI  / ( @INCOME - @OBLIGATIONS )) * 100;
		ELSE
			SELECT @ARR_FOIR = 0

		-- ARRIVED ROI
		DECLARE @ARR_ROI NUMERIC(27,2) ;
		SELECT  @ARR_ROI  = 18

		IF(@PrdCode = 'LAPTopup')
			SELECT  @ARR_ROI  = @ARR_ROI + 1;
		DECLARE @X_ARR_ROI NUMERIC(27,7) = @ARR_ROI / 12 / 100;
        DECLARE @Y_FACTOR NUMERIC(27,7) =  POWER((1 + @X_ARR_ROI), @TENURE);
        DECLARE @ARR_EMI NUMERIC(27,2) = @FINAL_LOAN_AMT * @X_ARR_ROI * @Y_FACTOR / (@Y_FACTOR- 1);


		IF(@PrdCode = 'LAPTopup')
		BEGIN
			SELECT @ARR_EMI = (@FINAL_LOAN_AMT - @OutSandAmt) * @X_ARR_ROI * @Y_FACTOR / (@Y_FACTOR- 1);
		END

		DECLARE @FIN_ARR_FOIR NUMERIC(27,2) 

		IF @INCOME <> 0
			SELECT @FIN_ARR_FOIR = ( @ARR_EMI / (@INCOME - @OBLIGATIONS)) * 100;
		ELSE
			SELECT @FIN_ARR_FOIR = 0

--SELECT @ARR_OutSandAmt , @FINAL_LOAN_AMT ,@TopUpAmt

		-- IF the product is BT+Topup or Topup 
		IF @PrdCode = 'LAPBTTopup' OR @PrdCode = 'LAPTopup'
		BEGIN
			
			SELECT @ARR_OutSandAmt = @OutSandAmt
						
			SELECT @TopUpAmt = @FINAL_LOAN_AMT - @OutSandAmt
			SELECT @ARR_TopUpAmt = @TopUpAmt 
			
			IF @FINAL_LOAN_AMT <= @OutSandAmt
			BEGIN
				SELECT @ARR_TopUpAmt = 0
				SELECT @ARR_OutSandAmt = @FINAL_LOAN_AMT
			END		

			SELECT @X_ARR_ROI = @ARR_ROI / 12 / 100;
			SELECT @Y_FACTOR =  POWER((1 + @X_ARR_ROI), @TENURE);
			SELECT @BT_EMI = ROUND(@ARR_OutSandAmt * @X_ARR_ROI * @Y_FACTOR / (@Y_FACTOR- 1),0);

			SELECT @X_ARR_ROI = (@ARR_ROI+1) / 12 / 100;
			SELECT @Y_FACTOR  =  POWER((1 + @X_ARR_ROI), @TENURE);
			SELECT @TOPUP_EMI = ROUND(@ARR_TopUpAmt * @X_ARR_ROI * @Y_FACTOR / (@Y_FACTOR- 1),0);			

			 
			IF @PrdCode = 'LAPTopup'
			BEGIN
				IF @MRKPROP_VAL <> 0
					SELECT @ARR_LTV = ((@FINAL_LOAN_AMT ) / @MRKPROP_VAL) * 100;
				ELSE
					SELECT @ARR_LTV = 0;

				IF @ACT_PRP_VAL <> 0
					SELECT @LTV_PERC_A =  ( (@FINAL_LOAN_AMT ) / @ACT_PRP_VAL ) * 100; 
				ELSE
					SELECT @LTV_PERC_A = 0

				SELECT @EXPLOAN = @EXPLOAN - @OutSandAmt
				SELECT @FINAL_LOAN_AMT = @FINAL_LOAN_AMT - @OutSandAmt
			END


			IF (@PrdCode = 'LAPBTTopup') 
            BEGIN
				SELECT @FIN_ARR_FOIR = ((@BT_EMI + @TOPUP_EMI ) / (@INCOME - @OBLIGATIONS)) * 100;
            END

		END		
		
		IF @PrdCode IN ('HLBT','HLTopup','HLBTTopup','LAPBT','LAPTopup','LAPBTTopup')
		BEGIN		
					
			IF @ACT_PRP_VAL <> 0
			BEGIN
				SELECT @BT_LTV_A  = (ISNULL(ROUND(@ARR_OutSandAmt,0),0) / @ACT_PRP_VAL ) * 100 ;
				SELECT @TOPUP_LTV_A  = (ISNULL(ROUND(@ARR_TopUpAmt,0),0) / @ACT_PRP_VAL ) * 100 ;
			END
			ELSE
			BEGIN	
				SELECT @BT_LTV_A  = 0
				SELECT @TOPUP_LTV_A  = 0
			END	

			IF @MRKPROP_VAL <> 0
			BEGIN
				SELECT @BT_LTV_M  = (ISNULL(ROUND(@ARR_OutSandAmt,0),0) / @MRKPROP_VAL ) * 100 ;
				SELECT @TOPUP_LTV_M  = (ISNULL(ROUND(@ARR_TopUpAmt,0),0) / @MRKPROP_VAL ) * 100 ;
			END
			ELSE
			BEGIN	
				SELECT @BT_LTV_M	= 0
				SELECT @TOPUP_LTV_M  = 0
			END									
		END
		ELSE
		BEGIN
			SELECT @BT_LTV_A	= 0
			SELECT @TOPUP_LTV_A  = 0
			SELECT @BT_LTV_M	= 0
			SELECT @TOPUP_LTV_M  = 0
		END
		
	
		INSERT INTO	@ReturnLoanTable(PRD_CODE,OUTSTD_AMT,ARR_OUTSTD_AMT,TOPUP_AMT,ARR_TOPUP_AMT,BT_EMI,TOPUP_EMI,LOAN_AMT,EMI,FOIR,ROI,
					LTV,EXP_LOAN_AMT,EXP_EMI,EXP_ROI,TENURE,CIBIL ,MRK_PRP,INCOME ,SAL_TYPE ,SAL_PRF,OBLIGATIONS,ACT_PRP_VAL, LTV_PERC_New,
					FOIR_PERC_New, SHPLR, Loan_Amt_New,ActLTV,BT_LTV_A,TOPUP_LTV_A,BT_LTV_M,TOPUP_LTV_M)
		SELECT		ISNULL(@PrdCode,''),ISNULL(ROUND(@OutSandAmt,0),0),ISNULL(ROUND(@ARR_OutSandAmt,0),0),ISNULL(ROUND(@TopUpAmt,0),0),ISNULL(ROUND(@ARR_TopUpAmt,0),0),ISNULL(ROUND(@BT_EMI,0),0),ISNULL(ROUND(@TOPUP_EMI,0),0),
					ISNULL(ROUND(@FINAL_LOAN_AMT,0),0) , ISNULL(ROUND(@ARR_EMI,0),0) , ISNULL(@FIN_ARR_FOIR,0), ISNULL(@ARR_ROI,0) , ISNULL(@ARR_LTV,0) , ISNULL(@EXPLOAN,0) , ISNULL(@EXP_EMI,0) , 
					ISNULL(@EXP_ROI,0) , ISNULL(@TENURE,0) , ISNULL(@CIBIL ,0),ISNULL(@MRKPROP_VAL,0),ISNULL(@INCOME,0),@SALARY_TYPE , @SAL_PROOF , ISNULL(@OBLIGATIONS,0),ISNULL(@ACT_PRP_VAL,0),
					@LTV_PERC, @FOIR, @SHPLR, @EXPLOAN,@LTV_PERC_A,@BT_LTV_A,@TOPUP_LTV_A,@BT_LTV_M,@TOPUP_LTV_M
		

		SELECT * FROM @ReturnLoanTable;
END



