SELECT  N'IF NOT EXISTS(SELECT ''X'' FROM [BpmUiDefn] WHERE BudPk='+  CAST(BudPk AS NVARCHAR(50)) 
        +N')BEGIN ' +  CHAR(5) + '
        SET IDENTITY_INSERT [dbo].[BpmUiDefn] ON ' +  CHAR(5) + ' 

        INSERT INTO [dbo].[BpmUiDefn]      ' +  CHAR(5) + '(
					[BudBfwFk], ' +  CHAR(5) + '
					[BudDesignTyp], ' +  CHAR(5) + '
					[BudDesignData], ' +  CHAR(5) + '
					[BudURL], ' +  CHAR(5) + '
					[BudDecIsAuto], ' +  CHAR(5) + '
					[BudDecExp], ' +  CHAR(5) + '
					[BudScript], ' +  CHAR(5) + '
					[BudNotes], ' +  CHAR(5) + '
					[BudPk], ' +  CHAR(5) + '
					[BudRowId], ' +  CHAR(5) + '
					[BudCreatedBy], ' +  CHAR(5) + '
					[BudCreatedDt], ' +  CHAR(5) + '
					[BudModifiedBy], ' +  CHAR(5) + '
					[BudModifiedDt], ' +  CHAR(5) + '
					[BudDelFlg], ' +  CHAR(5) + '
					[BudDelId], ' +  CHAR(5) + '
					[BudCd], ' +  CHAR(5) + '
					[BudIsRtnNeed]) ' +  CHAR(5) + '
             VALUES' +  CHAR(5) + ' 
                  ( '  + ISNULL(CAST(BudBfwFk AS NVARCHAR(1000)), 'NULL') + ' ' +  CHAR(5) + ' 
					, '  + ISNULL(CAST(BudDesignTyp AS NVARCHAR(1000)), 'NULL') + ' ' +  CHAR(5) + ' 
					, '''  + ISNULL(CAST(BudDesignData AS NVARCHAR(1000)), 'NULL') + ''' ' +  CHAR(5) + ' 
					, '''  + ISNULL(CAST(BudURL AS NVARCHAR(1000)), 'NULL') + ''' ' +  CHAR(5) + ' 
					, '  + ISNULL(CAST(BudDecIsAuto AS NVARCHAR(1000)), 'NULL') + ' ' +  CHAR(5) + ' 
					, '''  + ISNULL(CAST(BudDecExp AS NVARCHAR(1000)), 'NULL') + ''' ' +  CHAR(5) + ' 
					, '''  + ISNULL(CAST(BudScript AS NVARCHAR(1000)), 'NULL') + ''' ' +  CHAR(5) + ' 
					, '''  + ISNULL(CAST(BudNotes AS NVARCHAR(1000)), 'NULL') + ''' ' +  CHAR(5) + ' 
					, '  + ISNULL(CAST(BudPk AS NVARCHAR(1000)), 'NULL') + ' ' +  CHAR(5) + ' 
					, '''  + ISNULL(CAST(BudRowId AS NVARCHAR(1000)), 'NULL') + ''' ' +  CHAR(5) + ' 
					, '''  + ISNULL(CAST(BudCreatedBy AS NVARCHAR(1000)), 'NULL') + ''' ' +  CHAR(5) + ' 
					,dbo.gefgChar2Date(''' + dbo.gefgDMY(GETDATE()) + ''')' +  CHAR(5) + ' 
					, '''  + ISNULL(CAST(BudModifiedBy AS NVARCHAR(1000)), 'NULL') + ''' ' +  CHAR(5) + ' 
					,dbo.gefgChar2Date(''' + dbo.gefgDMY(GETDATE()) + ''')' +  CHAR(5) + ' 
					, '  + ISNULL(CAST(BudDelFlg AS NVARCHAR(1000)), 'NULL') + ' ' +  CHAR(5) + ' 
					, '  + ISNULL(CAST(BudDelId AS NVARCHAR(1000)), 'NULL') + ' ' +  CHAR(5) + ' 
					, '''  + ISNULL(CAST(BudCd AS NVARCHAR(1000)), 'NULL') + ''' ' +  CHAR(5) + ' 
					, '  + ISNULL(CAST(BudIsRtnNeed AS NVARCHAR(1000)), 'NULL') + ' ' +  CHAR(5) + ' 
                   ) ' +  CHAR(5) + ' 
        SET IDENTITY_INSERT [dbo].[BpmUiDefn] OFF ' +  CHAR(5) + ' 
        END ' +  CHAR(5) + ' 
        ' +  CHAR(5) + ' '+  CHAR(5)
FROM BpmUiDefn A
WHERE NOT EXISTS(SELECT 'X' FROM [SHFL_BPM_UAT]..[BpmUiDefn] B WHERE B.BudPk = A.BudPk)